# yaml-language-server: $schema=https://blue-build.org
name: pogos
description: operating system that is pog.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user
