name: BlueBuild
on:
  schedule:
    - cron: "0 17 * * 1"
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  bluebuild:
    name: Build Custom OS Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build Custom Image
        uses: blue-build/github-action@v1
        with:
          recipe: "recipes/recipe.yml"
          pr_event_number: ${{ github.event.number }}
          push: true
          # Force the CLI utility to completely ignore signing checks
          cli_flags: "--no-sign"
          
